import type { SBTTier } from "./types";

const LockDropSbt: SBTTier = {
	operationTitle: "Contribute to the Hive. Claim Your Place in the Future of BTCFi.",
	campaignTitle: "Hive Contributor",
	purpose:
		"Pull USDC, SUI, or WBTC commitments forward to seed Day-0 liquidity, then auto-convert to nbtc at mainnet.",
	tiers: [
		{
			tier: "I",
			name: "Seed Locker",
			requirement: "Commit $21 equivalent",
			description: "You locked your first $21 with Native.",
			bonusPercentage: 0,
			points: 21,
			totalPointsCumulative: 21,
		},
		{
			tier: "II",
			name: "Steady Locker",
			requirement: "Commit $100 equivalent",
			description: "Steady progress. You now have $100 locked.",
			bonusPercentage: 5,
			points: 105,
			totalPointsCumulative: 126,
		},
		{
			tier: "III",
			name: "Colony Locker",
			requirement: "Commit $500 equivalent",
			description: "You crossed the $500 lock milestone.",
			bonusPercentage: 10,
			points: 550,
			totalPointsCumulative: 676,
		},
		{
			tier: "IV",
			name: "Hive Saver",
			requirement: "Commit $2,100 equivalent",
			description: "Serious intent shown with $2,100 locked.",
			bonusPercentage: 15,
			points: 2415,
			totalPointsCumulative: 3091,
		},
		{
			tier: "V",
			name: "Vault Keeper",
			requirement: "Commit $5,000 equivalent",
			description: "Your $5,000 lock strengthens early markets.",
			bonusPercentage: 20,
			points: 6000,
			totalPointsCumulative: 9091,
		},
		{
			tier: "VI",
			name: "Honey Banker",
			requirement: "Commit $10,000 equivalent",
			description: "Five figures locked. Strong commitment.",
			bonusPercentage: 25,
			points: 12500,
			totalPointsCumulative: 21591,
		},
		{
			tier: "VII",
			name: "Reserve Builder",
			requirement: "Commit $21,000 equivalent",
			description: "Your $21k lock helps anchor the peg.",
			bonusPercentage: 30,
			points: 27300,
			totalPointsCumulative: 48891,
		},
		{
			tier: "VIII",
			name: "Guardian of TVL",
			requirement: "Commit $50,000 equivalent",
			description: "Among the largest lockers on Native.",
			bonusPercentage: 35,
			points: 67500,
			totalPointsCumulative: 116391,
		},
		{
			tier: "IX",
			name: "Sovereign Architect",
			requirement: "Commit $100,000 equivalent",
			description: "You architect the sovereign foundation of the Hive.",
			bonusPercentage: 45,
			points: 145000,
			totalPointsCumulative: 261391,
		},
		{
			tier: "X",
			name: "Master of the Vault",
			requirement: "Commit $210,000 equivalent",
			description: "Elite lock position secured for the hive.",
			bonusPercentage: 55,
			points: 325500,
			totalPointsCumulative: 586891,
		},
	],
};

const SocialSbt: SBTTier = {
	operationTitle: "Contribute to the Hive. Claim Your Place in the Future of BTCFi.",
	campaignTitle: "Hive Member",
	purpose:
		"link identities and build a light, repeatable engagement cadence. Proofs via Discord OAuth, X OAuth, signed link posts.",
	tiers: [
		{
			tier: "I",
			name: "Verified Visitor",
			requirement: "Connect Discord (OAuth)",
			description: "Joining the Native Discord is a big step. Welcome.",
			points: 10,
			totalPointsCumulative: 10,
		},
		{
			tier: "II",
			name: "Linked Broadcaster",
			requirement: "Connect X (OAuth)",
			description: "Your X account is linked. Your voice carries further.",
			points: 10,
			totalPointsCumulative: 20,
		},
		{
			tier: "III",
			name: "Native Follower",
			requirement: "Follow @goNativeCC (verified via OAuth)",
			description: "You follow Native. You’re close to the signal.",
			points: 30,
			totalPointsCumulative: 50,
		},
		{
			tier: "IV",
			name: "Verified Bee",
			requirement: "Join Discord + obtain Verified Bee role",
			description: "You verified in Discord. You’re officially part of the hive.",
			points: 50,
			totalPointsCumulative: 100,
		},
		{
			tier: "V",
			name: "BYield Profile",
			requirement: "Create a profile on BYield",
			description: "Your BYield profile is live. You’re ready to earn.",
			points: 100,
			totalPointsCumulative: 200,
		},
		{
			tier: "VI",
			name: "Pollen Seeker",
			requirement: "Obtain Pollen Seeker role",
			description: "You earned the Pollen Seeker role. Exploration started.",
			points: 200,
			totalPointsCumulative: 400,
		},
		{
			tier: "VII",
			name: "Buzzling",
			requirement: "Obtain Buzzling role",
			description: "You reached Buzzling status. Activity noted.",
			points: 400,
			totalPointsCumulative: 800,
		},
		{
			tier: "VIII",
			name: "Wingman",
			requirement: "Obtain Wingman role",
			description: "You earned the Wingman role. Reliable and helpful.",
			points: 400,
			totalPointsCumulative: 1200,
		},
		{
			tier: "IX",
			name: "Guardian of the Hive",
			requirement: "Obtain Guardian of the Hive role",
			description: "You’re a Guardian. You help keep the hive healthy.",
			points: 600,
			totalPointsCumulative: 1800,
		},
		{
			tier: "X",
			name: "Hive Master",
			requirement: "Obtain Hive Master role",
			description: "Hive Master achieved. Leadership recognized.",
			points: 700,
			totalPointsCumulative: 2500,
		},
	],
};

const ReferralSbt: SBTTier = {
	operationTitle: "Contribute to the Hive. Claim Your Place in the Future of BTCFi.",
	campaignTitle: "Hive Spreader",
	purpose: "grow high-quality users who actually bring more liquidity and growth.",
	tiers: [
		{
			tier: "I",
			name: "First Invite",
			requirement: 1,
			description: "Your first verified invite joined the hive.",
			points: 50,
			totalPointsCumulative: 50,
		},
		{
			tier: "II",
			name: "Network Starter",
			requirement: 3,
			description: "Three verified invites. The network is forming.",
			points: 100,
			totalPointsCumulative: 150,
		},
		{
			tier: "III",
			name: "Signal Booster",
			requirement: 5,
			description: "Five verified invites. Your signal is working.",
			points: 100,
			totalPointsCumulative: 250,
		},
		{
			tier: "IV",
			name: "Link Captain",
			requirement: 10,
			description: "Ten verified invites. Strong recruiting.",
			points: 350,
			totalPointsCumulative: 600,
		},
		{
			tier: "V",
			name: "Swarm Builder",
			requirement: 15,
			description: "Fifteen verified invites. Momentum building.",
			points: 400,
			totalPointsCumulative: 1000,
		},
		{
			tier: "VI",
			name: "Growth Operator",
			requirement: 25,
			description: "Twenty-five verified invites. Consistent growth.",
			points: 1000,
			totalPointsCumulative: 2000,
		},
		{
			tier: "VII",
			name: "Colony Lead",
			requirement: 40,
			description: "Forty verified invites. You lead a colony.",
			points: 1800,
			totalPointsCumulative: 3800,
		},
		{
			tier: "VIII",
			name: "Expansion Chief",
			requirement: 60,
			description: "Sixty verified invites. Reach is expanding.",
			points: 2800,
			totalPointsCumulative: 6600,
		},
		{
			tier: "IX",
			name: "Ecosystem Driver",
			requirement: 90,
			description: "Ninety verified invites. You drive the ecosystem.",
			points: 5400,
			totalPointsCumulative: 12000,
		},
		{
			tier: "X",
			name: "Swarm Architect",
			requirement: 130,
			description: "One-thirty verified invites. Network architect level.",
			points: 8000,
			totalPointsCumulative: 20000,
		},
	],
};

export { LockDropSbt, SocialSbt, ReferralSbt };
