# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "byield"
# url: https://byield.gonative.cc
# preview url:  *-byield.gonative-cc.workers.dev
compatibility_date = "2025-05-29"
compatibility_flags = [ "nodejs_compat" ]
main = "./server.ts"
minify = true

[vars]
VITE_APP_MODE = "production"
VITE_APP_NETWORK_MODE = "testnet"

[assets]
directory = "./build/client"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "byield-dev"
database_id = "e0772a14-1734-4eab-b193-84675dd08a20"
migrations_table = "migrations"
migrations_dir = "./db/migrations/"
